### ISSUE TITLE
answer_web_app_query

### ISSUE THREAD

**Issue by jdivanov77** [abdullaev388/Telegram-Web-App#2]
Hi,
In PTB v.13.13  I have problem using:
```
result = InlineQueryResultArticle(
            id=query_id,
            title='Order',
            input_message_content=InputTextMessageContent(message_text="result_text"))
bot.answer_web_app_query(web_app_query_id=query_id, result=result)
```

and I receive this error:
TypeError: Object of type InlineQueryResultArticle is not JSON serializable

I tried to put result in list [result] but I have the same error.
Did you have any idea where is the problem?

**Comment by abdullaev388** [comment]
Well i can't see how you imported ```InputTextMessageContent```
You should import types from telebot like this: ```from telebot import types```
And then try to get it from types: ```types.InputTextMessageContent```

**Comment by jdivanov77** [comment]
> Well i can't see how you imported `InputTextMessageContent` You should import types from telebot like this: `from telebot import types` And then try to get it from types: `types.InputTextMessageContent`

I am using python-telegram-bot and I try to use your example like this:
```
        init_data = parse_init_data(token=TOKEN, raw_init_data=data['initData'])
        if init_data is False:
            return False

        # bot: Bot = request.app['bot']
        query_id = init_data['query_id']

        result_text = "<b>Order summary:</b>\n\n"
        for item in data['items']:
            name, price, amount = item.values()
            result_text += f"{name} x{amount} — <b>{price}</b>\n"
        result_text += '\n' + data["totalPrice"]

        rr = InputTextMessageContent(message_text=result_text)
        result = InlineQueryResultArticle(
            id=query_id,
            title="Order",
            input_message_content=rr)
        bot.answer_web_app_query(query_id, result)
```
What you think?

**Comment by abdullaev388** [comment]
> > Well i can't see how you imported `InputTextMessageContent` You should import types from telebot like this: `from telebot import types` And then try to get it from types: `types.InputTextMessageContent`
> 
> I am using python-telegram-bot and I try to use your example like this:
> 
> ```
>         init_data = parse_init_data(token=TOKEN, raw_init_data=data['initData'])
>         if init_data is False:
>             return False
> 
>         # bot: Bot = request.app['bot']
>         query_id = init_data['query_id']
> 
>         result_text = "<b>Order summary:</b>\n\n"
>         for item in data['items']:
>             name, price, amount = item.values()
>             result_text += f"{name} x{amount} — <b>{price}</b>\n"
>         result_text += '\n' + data["totalPrice"]
> 
>         rr = InputTextMessageContent(message_text=result_text)
>         result = InlineQueryResultArticle(
>             id=query_id,
>             title="Order",
>             input_message_content=rr)
>         bot.answer_web_app_query(query_id, result)
> ```
> 
> What you think?

You probably should try to use keyword arguments when you call ```answer_web_app_query``` method.
So your code will look like:
Before: ```bot.answer_web_app_query(query_id, result)```
After: ```bot.answer_web_app_query(web_app_query_id=query_id, result=result)```
